global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using CommunityToolkit.Mvvm;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using DevUtils;
global using DevUtils.Converters;
global using DevUtils.Shared;